name: Build Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9

      - name: Build mod jar
        run: gradle build --stacktrace --no-daemon

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: horrormod-jar
          path: build/libs/*.jar
